#!/bin/sh

#start imlink
ifconfig wlan0 up 2> /dev/null 1> /dev/null
imlink-mon stop mon0  2> /dev/null 1> /dev/null
imlink-mon start wlan0  2> /dev/null 1> /dev/null
ifconfig wlan0 down  2> /dev/null 1> /dev/null
ifconfig wlan0-1 down  2> /dev/null 1> /dev/null

#. /home/intorobot/intorobot_log_tool/intorobot_log_tool.sh
#print_inf "[$0 info]:cmd=$0 $*"

echo "------------------------------------------------------------"
echo "usage:   $0 ssid [CH SEC]"        
echo "example: $0 xiaomi CH"   
echo "------------------------------------------------------------"
#exit 1

while :;do 
  success=0
  rgb_control blink 255 0 0 1000
  ap_info=`imlink-dump |grep ImlinkResult`
  ap_info=`echo ${ap_info#*:}`
  echo $ap_info
  source_ip=`echo ${ap_info#*:} | awk -F ',' '{print $1}'`
  echo $source_ip
  ssid=`echo ${ap_info} | awk -F ','  '{print $2}'`
  ssid=${ssid#*:}
  echo $ssid
  enc=`echo ${ap_info} | awk -F ',' '{print $3}'`
  enc=${enc#*:}
  echo $enc
  auth=`echo ${ap_info} | awk -F ',' '{print $4}'`
  auth=${auth#*:}
  echo $auth
  password=`echo ${ap_info} | awk -F ',' '{print $5}'`
  password=${password#*:}
  echo $password
  channel=`echo ${ap_info} | awk -F ',' '{print $6}'`
  channel=${channel#*:}
  echo $channel
  bssid=`echo ${ap_info} | awk -F ',' '{print $7}'`
  bssid=${bssid#*:}
  echo $bssid

  uci set network.wwan='interface'
  uci set network.wwan.proto='dhcp'
  uci commit network
  uci set wireless.@wifi-device[0].channel=${channel}
  uci set wireless.atom_ap.disabled='1'
  uci set wireless.atom_sta.device='radio0'
  uci set wireless.atom_sta.network='wwan'
  uci set wireless.atom_sta.mode='sta'
  uci set wireless.atom_sta.ssid=${ssid}
  uci set wireless.atom_sta.key=${password}
  uci set wireless.atom_sta.encryption=${auth}
  uci commit wireless
  uci set firewall.@zone[1].network='wan wan6'
  uci commit firewall
  /etc/init.d/firewall restart  2> /dev/null 1> /dev/null
  /etc/init.d/network restart  2> /dev/null 1> /dev/null
  /etc/init.d/dnsmasq restart  2> /dev/null 1> /dev/null

  rgb_control blink 255 0 0 400
  count=1;
  while :;do
    ping ${source_ip} -w100 -c 1
    if [ $? == 0 ]
    then
      success=1
      break
    fi
    count=$(($count+1))
    echo $count
    if [ $count -gt 300 ]
    then
      rgb_control blink 255 0 0 3000
      echo "Ping timeout"
      break
    fi
    usleep 100000 
  done
  if [ $success -eq 1 ];then
    break;
  fi

  imlink-mon stop mon0  2> /dev/null 1> /dev/null
  imlink-mon start wlan0  2> /dev/null 1> /dev/null
  ifconfig wlan0 down  2> /dev/null 1> /dev/null
  ifconfig wlan0-1 down  2> /dev/null 1> /dev/null
done

rgb_control blink 255 0 0 100
while :;do 
   if [ ! $password ]; then
     imlink-response -s ${ssid} -b ${bssid} -p 18266 -i ${source_ip}  
   else
     imlink-response -s ${ssid} -w ${password} -b ${bssid} -p 18266 -i ${source_ip}  
   fi
   usleep 500000
done

exit 0
