#!/bin/sh

airmon-ng stop mon0
airmon-ng start wlan0
ifconfig wlan0 down

#. /home/intorobot/intorobot_log_tool/intorobot_log_tool.sh
#print_inf "[$0 info]:cmd=$0 $*"

echo "------------------------------------------------------------"
echo "usage:   $0 ssid [CH SEC]"        
echo "example: $0 xiaomi CH"   
echo "------------------------------------------------------------"
#exit 1

ap_info=`smartconfig-dump |grep SmartconfigResult`
#echo "$ap_info"

ap_info=`echo ${ap_info#*:}`
echo $ap_info
source_ip=`echo ${ap_info#*:} | awk '{print $1}'`
echo $source_ip
ssid=`echo ${ap_info} | awk '{print $2}'`
ssid=${ssid#*:}
echo $ssid
enc=`echo ${ap_info} | awk '{print $3}'`
enc=${enc#*:}
echo $enc
auth=`echo ${ap_info} | awk '{print $4}'`
auth=${auth#*:}
echo $auth
password=`echo ${ap_info} | awk '{print $5}'`
password=${password#*:}
if [ ! $password ]; then
	password=none
fi
echo $password
channel=`echo ${ap_info} | awk '{print $6}'`
channel=${channel#*:}
echo $channel
bssid=`echo ${ap_info} | awk '{print $7}'`
bssid=${bssid#*:}
echo $bssid

uci set network.wwan='interface'
uci set network.wwan.proto='dhcp'
uci commit network
uci set wireless.@wifi-device[0].channel=${channel}
uci set wireless.@wifi-iface[1].device='radio0'
uci set wireless.@wifi-iface[1].network='wwan'
uci set wireless.@wifi-iface[1].mode='sta'
uci set wireless.@wifi-iface[1].ssid=${ssid}
uci set wireless.@wifi-iface[1].key=${password}
uci set wireless.@wifi-iface[1].encryption=${auth}
uci commit wireless
/etc/init.d/network restart

echo "send data to port 18266"
echo `smartconfig-response -s ${ssid} -w ${password} -b ${bssid} -p 18266 -i ${source_ip}` 

#echo "send data to port 5557"
#echo `smartconfig-response -s ${ssid} -w ${password} -b ${bssid} -p  5557 -i ${source_ip}` 

exit 1
